import type { Match, Prediction, User } from "./domain";

export const seedMatches: Match[] = [
  {
    id: "wc26-mex-rsa",
    group: "Group A",
    homeTeam: "Mexico",
    awayTeam: "South Africa",
    kickoff: "2026-06-11T15:00:00-04:00",
    venue: "Mexico City Stadium",
    status: "finished",
    homeScore: 2,
    awayScore: 0,
  },
  {
    id: "wc26-kor-cze",
    group: "Group A",
    homeTeam: "Korea Republic",
    awayTeam: "Czechia",
    kickoff: "2026-06-11T21:00:00-04:00",
    venue: "Guadalajara Stadium",
    status: "finished",
    homeScore: 1,
    awayScore: 1,
  },
  {
    id: "wc26-can-bih",
    group: "Group B",
    homeTeam: "Canada",
    awayTeam: "Bosnia and Herzegovina",
    kickoff: "2026-06-12T15:00:00-04:00",
    venue: "Toronto Stadium",
    status: "finished",
    homeScore: 1,
    awayScore: 0,
  },
  {
    id: "wc26-usa-par",
    group: "Group D",
    homeTeam: "USA",
    awayTeam: "Paraguay",
    kickoff: "2026-06-12T21:00:00-04:00",
    venue: "Los Angeles Stadium",
    status: "finished",
    homeScore: 4,
    awayScore: 1,
  },
  {
    id: "wc26-ger-cur",
    group: "Group E",
    homeTeam: "Germany",
    awayTeam: "Curacao",
    kickoff: "2026-06-15T12:00:00-04:00",
    venue: "Houston Stadium",
    status: "finished",
    homeScore: 7,
    awayScore: 1,
  },
  {
    id: "wc26-sau-uru",
    group: "Group H",
    homeTeam: "Saudi Arabia",
    awayTeam: "Uruguay",
    kickoff: "2026-06-15T15:00:00-04:00",
    venue: "Miami Stadium",
    status: "scheduled",
  },
  {
    id: "wc26-esp-cpv",
    group: "Group H",
    homeTeam: "Spain",
    awayTeam: "Cabo Verde",
    kickoff: "2026-06-15T18:00:00-04:00",
    venue: "Atlanta Stadium",
    status: "scheduled",
  },
  {
    id: "wc26-ira-nzl",
    group: "Group G",
    homeTeam: "IR Iran",
    awayTeam: "New Zealand",
    kickoff: "2026-06-15T21:00:00-04:00",
    venue: "Los Angeles Stadium",
    status: "scheduled",
  },
  {
    id: "wc26-fra-sen",
    group: "Group I",
    homeTeam: "France",
    awayTeam: "Senegal",
    kickoff: "2026-06-16T15:00:00-04:00",
    venue: "New York New Jersey Stadium",
    status: "scheduled",
  },
  {
    id: "wc26-arg-alg",
    group: "Group J",
    homeTeam: "Argentina",
    awayTeam: "Algeria",
    kickoff: "2026-06-16T21:00:00-04:00",
    venue: "Kansas City Stadium",
    status: "scheduled",
  },
  {
    id: "wc26-bra-hai",
    group: "Group C",
    homeTeam: "Brazil",
    awayTeam: "Haiti",
    kickoff: "2026-06-19T18:00:00-04:00",
    venue: "Philadelphia Stadium",
    status: "scheduled",
  },
  {
    id: "wc26-arg-aut",
    group: "Group J",
    homeTeam: "Argentina",
    awayTeam: "Austria",
    kickoff: "2026-06-22T18:00:00-04:00",
    venue: "Dallas Stadium",
    status: "scheduled",
  },
  {
    id: "wc26-eng-gha",
    group: "Group L",
    homeTeam: "England",
    awayTeam: "Ghana",
    kickoff: "2026-06-23T15:00:00-04:00",
    venue: "Boston Stadium",
    status: "scheduled",
  },
  {
    id: "wc26-sco-bra",
    group: "Group C",
    homeTeam: "Scotland",
    awayTeam: "Brazil",
    kickoff: "2026-06-24T15:00:00-04:00",
    venue: "Miami Stadium",
    status: "scheduled",
  },
];

export const demoUsers: User[] = [
  { id: "u-alex", name: "Alex", email: "alex@lab.edu", method: "simple" },
  { id: "u-mina", name: "Mina", email: "mina@lab.edu", method: "simple" },
  { id: "u-rafa", name: "Rafa", email: "rafa@lab.edu", method: "simple" },
];

export const seedPredictions: Prediction[] = [
  {
    id: "p1",
    matchId: "wc26-mex-rsa",
    userId: "u-mina",
    userName: "Mina",
    homeScore: 2,
    awayScore: 0,
    submittedAt: "2026-06-10T18:22:00-04:00",
  },
  {
    id: "p2",
    matchId: "wc26-mex-rsa",
    userId: "u-rafa",
    userName: "Rafa",
    homeScore: 1,
    awayScore: 0,
    submittedAt: "2026-06-10T18:32:00-04:00",
  },
  {
    id: "p3",
    matchId: "wc26-usa-par",
    userId: "u-mina",
    userName: "Mina",
    homeScore: 3,
    awayScore: 1,
    submittedAt: "2026-06-11T10:02:00-04:00",
  },
  {
    id: "p4",
    matchId: "wc26-ger-cur",
    userId: "u-rafa",
    userName: "Rafa",
    homeScore: 3,
    awayScore: 0,
    submittedAt: "2026-06-14T08:44:00-04:00",
  },
  {
    id: "p5",
    matchId: "wc26-bra-hai",
    userId: "u-mina",
    userName: "Mina",
    homeScore: 2,
    awayScore: 0,
    submittedAt: "2026-06-14T11:01:00-04:00",
  },
];
